export const items = [
    {
        "name": "Netflix",
        "site": "www.netflix.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "tejas#123",
        "isFavorite": true,
        "type": "Logins",
        "category": "Streaming",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=yPOgUFWHVx7X&format=png&color=000000"
    },
    {
        "name": "Amazon Prime",
        "site": "www.amazon.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "prime#123",
        "isFavorite": false,
        "type": "Logins",
        "category": "Streaming",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=mJTj7Q9EPSVn&format=png&color=000000"
    },
    {
        "name": "Hulu",
        "site": "www.hulu.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "hulu#123",
        "isFavorite": true,
        "type": "Logins",
        "category": "Streaming",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=TG5b2eR21DuF&format=png&color=000000"
    },
    {
        "name": "Disney+",
        "site": "www.disneyplus.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "disney#123",
        "isFavorite": false,
        "type": "Logins",
        "category": "Streaming",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=UgLZ7UHMfzU5&format=png&color=000000"
    },
    {
        "name": "HBO Max",
        "site": "www.hbomax.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "hbomax#123",
        "isFavorite": true,
        "type": "Logins",
        "category": "Streaming",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=lZfOrvLHxy9S&format=png&color=000000"
    },
    {
        "name": "Spotify",
        "site": "www.spotify.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "spotify#123",
        "isFavorite": false,
        "type": "Logins",
        "category": "Streaming",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=0wzAMt8KO1C6&format=png&color=000000"
    },
    {
        "name": "Apple TV+",
        "site": "www.apple.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "appletv#123",
        "isFavorite": true,
        "type": "Logins",
        "category": "Streaming",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=erlocm5T9jvM&format=png&color=000000"
    },
    {
        "name": "YouTube",
        "site": "www.youtube.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "youtube#123",
        "isFavorite": false,
        "type": "Logins",
        "category": "Social Media",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=9itS6I2x2vV2&format=png&color=000000"
    },
    {
        "name": "Twitch",
        "site": "www.twitch.tv",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "twitch#123",
        "isFavorite": true,
        "type": "Logins",
        "category": "Social Media",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=XTmPgiLA41sk&format=png&color=000000"
    },
    {
        "name": "Twitter",
        "site": "www.twitter.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "twitter#123",
        "isFavorite": false,
        "type": "Logins",
        "category": "Social Media",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=kbuAJVwYUPvh&format=png&color=000000"
    },
    {
        "name": "Facebook",
        "site": "www.facebook.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "facebook#123",
        "isFavorite": true,
        "type": "Logins",
        "category": "Social Media",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=8818&format=png&color=000000"
    },
    {
        "name": "Instagram",
        "site": "www.instagram.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "instagram#123",
        "isFavorite": false,
        "type": "Logins",
        "category": "Social Media",
        "lastModified": "2024-06-02T00:00:00Z",
        // "logo": "https://upload.wikimedia.org/wikipedia/commons/a/a5/Instagram_icon.png"
        "logo": "https://img.icons8.com/?size=100&id=Xy10Jcu1L2Su&format=png&color=000000"
    },
    {
        "name": "LinkedIn",
        "site": "www.linkedin.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "linkedin#123",
        "isFavorite": true,
        "type": "Logins",
        "category": "Social Media",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=xuvGCOXi8Wyg&format=png&color=000000"
    },
    {
        "name": "Reddit",
        "site": "www.reddit.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "reddit#123",
        "isFavorite": false,
        "type": "Logins",
        "category": "Social Media",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=5RTQxy0E0NUY&format=png&color=000000"
    },
    {
        "name": "WhatsApp",
        "site": "www.whatsapp.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "whatsapp#123",
        "isFavorite": true,
        "type": "Logins",
        "category": "Social Media",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=UBjTW632xuVM&format=png&color=000000"
    },
    {
        "name": "Steam",
        "site": "www.steampowered.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "steam#123",
        "isFavorite": false,
        "type": "Logins",
        "category": "Gaming",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=12505&format=png&color=000000"
    },
    {
        "name": "Epic Games",
        "site": "www.epicgames.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "epicgames#123",
        "isFavorite": true,
        "type": "Logins",
        "category": "Gaming",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=bCP28brs5BYg&format=png&color=000000"
    },
    {
        "name": "PayPal",
        "site": "www.paypal.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "paypal#123",
        "isFavorite": false,
        "type": "Logins",
        "category": "Finance",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=CcZPuP1Awed7&format=png&color=000000"
    },
    {
        "name": "Chase",
        "site": "www.chase.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "chase#123",
        "isFavorite": false,
        "type": "Logins",
        "category": "Finance",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=65313&format=png&color=000000"
    },
    {
        "name": "Venmo",
        "site": "www.venmo.com",
        "username": "tejas",
        "email": "tejas@example.com",
        "password": "venmo#123",
        "isFavorite": true,
        "type": "Logins",
        "category": "Finance",
        "lastModified": "2024-06-02T00:00:00Z",
        "logo": "https://img.icons8.com/?size=100&id=iJIbu0YIn6lA&format=png&color=000000"
    }
]

export default items;